### ISSUE TITLE
Jitter in the results provided. 

### ISSUE THREAD

**Issue by charchit7** [ibaiGorordo/ONNX-SAM2-Segment-Anything#1]
Hey, nice work. Just wanted to know if the jitter in the result was due to model or your pipeline? For example, the two dog images you have provided have jitter in the masks.

**Comment by ibaiGorordo** [comment]
It is possible that I might have missed something in the conversion. Also, some of the postprocessing is not the same (for example the mask upscaling is smoother in the official repo). 

Here is the result comparison:

**Official repo:**
![dogs_output](https://github.com/user-attachments/assets/5cf4c1dc-958b-4a43-8e07-159e207a13ea)

**This repo:**
![sam2_masked_img](https://github.com/user-attachments/assets/53e3a4bb-d82f-4a65-a5ba-840bb3c0e93b)

**Comment by charchit7** [comment]
Got it, I'll also look into it.

**Comment by ibaiGorordo** [comment]
Added them to the release:
https://github.com/ibaiGorordo/ONNX-SAM2-Segment-Anything/releases/tag/0.1.0

**Comment by ibaiGorordo** [comment]
Results after the latest changes:
![sam2_masked_img](https://github.com/user-attachments/assets/45ab7eeb-2593-475c-bf17-297e4c1b063e)

**Comment by charchit7** [comment]
Hey, nice,  by not updating the `masks = self.sam2.update_mask(True)` ?

**Comment by ibaiGorordo** [comment]
Modified the Pytorch model for the export to multimask_output=False, and changed the code in this repository accordingly

I recommend pulling the latest changes and download the new models from: https://github.com/ibaiGorordo/ONNX-SAM2-Segment-Anything/releases/tag/0.2.0

**Comment by charchit7** [comment]
Got it, thank you so much. @ibaiGorordo will update it :)

**Comment by charchit7** [comment]
Hey, are you planning to convert sam2_hiera_large model too. 
Currently I am trying to get model from https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/tree/main to try your codebase.

**Comment by charchit7** [comment]
Also, while converting the model to onnx, my system is getting crashed. 

```
(cs_seg) charchit@a10x1-4v-16g-s1-0-dy-compute-1:~$ python /home/charchit/private_repo/segment-anything-2/convert_onnx.py
torch.Size([1, 32, 256, 256])
torch.Size([1, 64, 128, 128])
torch.Size([1, 256, 64, 64])
/home/charchit/private_repo/segment-anything-2/sam2/modeling/backbones/utils.py:30: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_h > 0 or pad_w > 0:
/home/charchit/private_repo/segment-anything-2/sam2/modeling/backbones/utils.py:60: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if Hp > H or Wp > W:
Killed

using your colab code only. 
```

**Comment by charchit7** [comment]
Ram issues, I think.

**Comment by ibaiGorordo** [comment]
> Hey, are you planning to convert sam2_hiera_large model too. Currently I am trying to get model from https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/tree/main to try your codebase.

Just added the large model to the latest release and renamed the decoder
