### ISSUE TITLE
Use this Google Colab notebook to convert the encoder and decoder models

### ISSUE THREAD

**Issue by jakko10** [ibaiGorordo/ONNX-SAM2-Segment-Anything#3]
It's a nice idea but without a subscription, the free tier VM crashes due to lack of memory, and you never get the models.
Edit;
Looks like the files are available here:
https://huggingface.co/vietanhdev/segment-anything-2-onnx-models/tree/main
but the file names are a bit different.
For example:
sam2_hiera_base_plus.decoder.onnx -> sam2_hiera_base_plus_decoder.onnx
sam2_hiera_base_plus.encoder.onnx  -> sam2_hiera_base_plus_encoder.onnx

**Comment by ibaiGorordo** [comment]
With the latest changes, other models will not work. Use these models:
https://github.com/ibaiGorordo/ONNX-SAM2-Segment-Anything/releases/tag/0.2.0
