### ISSUE TITLE
Input Box infer 

### ISSUE THREAD

**Issue by BaiCHao12** [ibaiGorordo/ONNX-SAM2-Segment-Anything#5]
Input Box infer  in onnx model

**Comment by ibaiGorordo** [comment]
I will try to get it working on the weekend

**Comment by ibaiGorordo** [comment]
Closing as added:
![!ONNX-SAM2-Segment-Anything](https://github.com/ibaiGorordo/ONNX-SAM2-Segment-Anything/raw/main/doc/img/sam2_mask_with_boxes.png)
